export function objectNames(o){
 const normalise=s=>String(s||'').replace(/^(NGC|IC|M)\s*0*(\d+)/i,(_,prefix,n)=>prefix.toUpperCase()+' '+Number(n));
 return [...new Set([o.id,o.name,o.ngc,...o.aliases].filter(Boolean).map(normalise))];
}
const kinds={Galaxy:'Galaxies are vast systems of stars, gas and dust; their apparent brightness is spread over their visible area.','Galaxy group':'A galaxy group contains multiple galaxies seen together in a region of sky.','Emission nebula':'Emission nebulae glow as gas is energised by nearby stars. Their faint outer regions can extend beyond the brighter structures.','Reflection nebula':'Reflection nebulae are dust clouds that scatter the light of nearby stars.','Planetary nebula':'A planetary nebula is an expanding shell of gas shed by an evolved star; the name does not refer to planets.','Supernova remnant':'Supernova remnants are expanding material left by stellar explosions.','Open cluster':'Open clusters are relatively loose groups of stars formed together.','Globular cluster':'Globular clusters are dense, roughly spherical concentrations of stars.','Dark nebula':'Dark nebulae are clouds of dust seen by the light they block from objects behind them.','Cluster + nebula':'This catalogue entry combines a star cluster with surrounding nebulosity.',Nebula:'Nebulae are clouds of interstellar gas or dust. The catalogue does not specify a more detailed type for this entry.','Star association':'Stellar associations are loose groupings of stars.'};
export function catalogueDescription(o){
 const size=o.major==null?'Its apparent size is not recorded in this catalogue.':`Its catalogued long axis spans ${o.major.toFixed(2)} arcminutes${o.minor!=null?`, with a short axis of ${o.minor.toFixed(2)} arcminutes`:''}.`;
 return `${objectNames(o).slice(0,3).join(' / ')} is catalogued as ${o.type.toLowerCase()} in the constellation ${o.constellation}. ${kinds[o.type]||''} ${size} ${o.mag==null?'No integrated magnitude is available.':`Its integrated ${o.band||''}-band magnitude is ${o.mag.toFixed(2)}; this describes total light rather than brightness per unit area.`}`;
}
