import {test,expect} from '@playwright/test';
test('Edit corners, cancel changes, preserve patch filtering and read offline changelog',async({page,context})=>{
 await page.goto('/');await page.waitForFunction(()=>window.skyPatch);await page.locator('#patchTab').click();await expect(page.locator('#patchTab')).toHaveText('My Sky');await page.locator('#drawPatch').click();const r=await page.locator('#overlay').boundingBox();
 for(const [x,y]of [[.3,.3],[.65,.3],[.65,.6],[.3,.6]])await page.mouse.click(r.x+r.width*x,r.y+r.height*y);
 await page.locator('#finishPatch').click();const original=await page.evaluate(()=>skyPatch.state.patch.vertices);
 await page.locator('#editPatch').click();await expect(page.locator('.patch-handle').first()).toBeVisible();const h=await page.locator('.patch-handle').first().boundingBox();await page.mouse.move(h.x+22,h.y+22);await page.mouse.down();await page.mouse.move(h.x+50,h.y+35,{steps:5});await page.mouse.up();await page.locator('#finishPatch').click();const edited=await page.evaluate(()=>skyPatch.state.patch.vertices);expect(edited[0]).not.toEqual(original[0]);expect(edited.slice(1)).toEqual(original.slice(1));
 await page.locator('#editPatch').click();await page.locator('.patch-handle').first().focus();await page.keyboard.press('ArrowRight');await page.locator('#cancelPatch').click();expect(await page.evaluate(()=>skyPatch.state.patch.vertices)).toEqual(edited);
 await page.locator('#filtersTab').click();await page.locator('#filtersEnabled').uncheck();expect(await page.evaluate(()=>skyPatch.objects.some(o=>o.reasons.includes('Outside sky patch')))).toBe(true);
 await page.locator('#appStatus').click();await expect(page.locator('#appModeStatus')).toContainText('Online');await context.setOffline(true);await expect(page.locator('#appStatus')).toHaveText('○ Offline');await page.getByText('Version history / changelog',{exact:true}).click();await expect(page.locator('.release-history')).toContainText('0.6.0');
});
test('Touch can drag a patch corner',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();await page.addInitScript(()=>localStorage.setItem('skypatch-install-prompt-seen','true'));await page.goto('/');await page.waitForFunction(()=>window.skyPatch);await page.locator('#sidebarToggle').tap();await page.locator('#patchTab').tap();await page.locator('#drawPatch').tap();
 for(const [x,y]of [[100,200],[250,200],[250,320],[100,320]])await page.touchscreen.tap(x,y);await page.locator('#finishPatch').tap();await page.locator('#sidebarToggle').tap();const before=await page.evaluate(()=>skyPatch.state.patch.vertices);await page.locator('#editPatch').tap();await expect(page.locator('.patch-handle').first()).toBeVisible();const h=await page.locator('.patch-handle').first().boundingBox(),client=await context.newCDPSession(page);
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:h.x+22,y:h.y+22,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:h.x+42,y:h.y+32,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.locator('#finishPatch').tap();expect(await page.evaluate(()=>skyPatch.state.patch.vertices[0])).not.toEqual(before[0]);await context.close();
});
